// <auto-generated />
namespace WineRoomAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatingdatestodatetimetypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatingdatestodatetimetypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201704211423374_updating dates to datetime types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
